# Generated by Django 5.1.15 on 2026-05-26 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('servers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password_display', models.CharField(blank=True, help_text='Shown once at creation, then cleared.', max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='active', max_length=12)),
                ('expire_date', models.DateTimeField()),
                ('max_connections', models.PositiveIntegerField(default=1)),
                ('bandwidth_limit_gb', models.PositiveIntegerField(default=0)),
                ('bandwidth_used_gb', models.FloatField(default=0)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='plans.plan')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssh_accounts', to='servers.server')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('username', 'server')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('delete', 'Delete'), ('suspend', 'Suspend'), ('activate', 'Activate'), ('extend', 'Extend'), ('expire', 'Expire'), ('password_reset', 'Password Reset'), ('rebalance', 'Rebalance')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounts.sshaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('connected_since', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.sshaccount')),
            ],
            options={
                'unique_together': {('account', 'pid')},
            },
        ),
    ]
