# Generated by Django 5.1.15 on 2026-05-26 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('ssh_port', models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('ssh_user', models.CharField(default='root', max_length=64)),
                ('ssh_key_path', models.CharField(help_text='Absolute path to private key on the panel server.', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('full', 'Full'), ('down', 'Down')], default='active', max_length=15)),
                ('location', models.CharField(blank=True, help_text='e.g. Frankfurt, DE', max_length=120)),
                ('max_users', models.PositiveIntegerField(default=100)),
                ('cpu_usage', models.FloatField(default=0, help_text='Percentage')),
                ('ram_usage', models.FloatField(default=0, help_text='Percentage')),
                ('disk_usage', models.FloatField(default=0, help_text='Percentage')),
                ('uptime_seconds', models.BigIntegerField(default=0)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
